### ISSUE TITLE
Not working with object destructuring

### ISSUE THREAD

**Issue by leonardiwagner** [arrizalamin/js-function-reflector#6]
Hi @arrizalamin , first of all , I'd like you to thank you for this library, it's the best by far for ES2015 functions reflections, the [z](https://github.com/z-pattern-matching/z) project relies on it, thank you so much!

I think @Koleok got one of the latest bugs, which is, it doesn't get object destructuring as parameter:
```javascript
functionReflector(({ name, age }) => {})) 
//result: {"name":"anonymous","args":["{name","age}"],"body":""}
```

it becomes easier to see the bug when put together with other working args, such:
```javascript
functionReflector(functionReflector((x = 1, y, { name, age }) => {})))
//result: {"name":"anonymous","args":[["x",1],"y","{name","age}"],"body":""}
```

Since args works as argument -> argument name, argument with value comparison -> array where first position is argument name and second is value, my suggestion is where is argument as destructuring it becames an object, like:

returning suggestion from `functionReflector(functionReflector((x = 1, y, { name, age }) => {})))`: 
`{"name":"anonymous","args":[["x",1],"y",{ destructuring: ["name","age"] },"body":""}`

**Comment by arrizalamin** [comment]
thanks for the report, it turns out this doesn't parse array destructuring either. so, I think destructuring argument should be `{destructuring: "object/array", keys: ["name", "age"]}`.
btw, last year I made a similar library like [z](https://github.com/z-pattern-matching/z) for my redux app with this reflector https://github.com/arrizalamin/jala 😀.
